### ISSUE TITLE
과제

### ISSUE THREAD

**Issue by kreimben** [Team-Discipline/URLS3-backend#1]
@ryankimjh00 @ss35789 @JungHanLeee @gka0903 

각자 URL단축 사이트들과 그들의 사례를 조사 하고 어떤 방식으로 작동되는지에 관해 조사해 올것. (19일 미팅때 정리해서 발표하기)

**Comment by ryankimjh00** [comment]
obsidian://open?vault=obsidian-git-sync&file=Portfolio%2FProjects%2FURLsss%2Furl%20%EB%8B%A8%EC%B6%95%20%EC%84%9C%EB%B9%84%EC%8A%A4%20%EA%B8%B0%EC%88%A0%20%EC%8A%A4%ED%83%9D
