### ISSUE TITLE
Help me

### ISSUE THREAD

**Issue by ryankimjh00** [Team-Discipline/URLS3-backend#35]
I made URL validator and the migration went smoothly. So I think there seems to be no error in the function. But I got an error when I run my test code. 
```
(interpreter) PS C:\Users\Jonghyeon Kim\Documents\GitHub\URLS3-backend> python manage.py test urlvalidator.test
Found 1 test(s).
System check identified no issues (0 silenced).
E
======================================================================
ERROR: test (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test
Traceback (most recent call last):
  File "C:\Python310\lib\unittest\loader.py", line 154, in loadTestsFromName
    module = __import__(module_name)
ModuleNotFoundError: No module named 'urlvalidator.test'


Ran 1 test in 0.000s
```

Please tell me how to solve it if you've got such errors before.

commit is here 097e5317c8e47da432fe8117a4705d51a89f7657

**Comment by kreimben** [comment]
https://github.com/Team-Discipline/URLS3-backend/commit/097e5317c8e47da432fe8117a4705d51a89f7657#commitcomment-84994899


https://www.youtube.com/watch?v=1FqxfnlQPi8
https://www.youtube.com/watch?v=0EmvB9fvmsA
https://www.youtube.com/watch?v=0OOS7sbVn4U

**Comment by ryankimjh00** [comment]
> [097e531#commitcomment-84994899](https://github.com/Team-Discipline/URLS3-backend/commit/097e5317c8e47da432fe8117a4705d51a89f7657#commitcomment-84994899)
> 
> https://www.youtube.com/watch?v=1FqxfnlQPi8 https://www.youtube.com/watch?v=0EmvB9fvmsA https://www.youtube.com/watch?v=0OOS7sbVn4U

thanks!
